Web/Source/BloomSales.Web.Store/Controllers/ProductController.cs
using BloomSales.Services.Contracts;
using BloomSales.Services.Proxies;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BloomSales.Web.Store.Controllers
{
    public class ProductController : Controller
    {
        private IInventoryService inventoryService;

        public ProductController()
        {
            inventoryService = new InventoryClient();
        }

        public ActionResult Details(int id)
        {
            var product = inventoryService.GetProductByID(id);

            return PartialView(product);
        }
    }
}

Web/Source/BloomSales.Web.Store/Controllers/ShoppingCartController.cs
using BloomSales.Data.Entities;
using BloomSales.Services.Contracts;
using BloomSales.Services.Proxies;
using BloomSales.Web.Store.Controllers.Business;
using BloomSales.Web.Store.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BloomSales.Web.Store.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IOrderService orderService;
        private IInventoryService inventoryService;

        public ShoppingCartController()
        {
            orderService = new OrderClient();
            inventoryService = new InventoryClient();
        }

        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = GetShoppingCart();
            var productIDs = cart.ItemsProductIDs;

            var products = inventoryService.GetProductsByIDs(productIDs);
            var items = new List<OrderItem>(cart.Items);

            Tuple<List<OrderItem>, IEnumerable<Product>> cartItems =
                new Tuple<List<OrderItem>, IEnumerable<Product>>(items, products);

            return View(cartItems);
        }

        public ActionResult Count()
        {
            var cart = GetShoppingCart();

            return PartialView(cart.NumberOfItems);
        }

        [HttpPost]
        public ActionResult Add(ProductDetailsViewModel productDetails)
        {
            OrderItem item = new OrderItem();
            item.ProductID = productDetails.ID;
            item.Quantity = 1;
            item.UnitPrice = productDetails.UnitPrice;

            var cart = GetShoppingCart();
            cart.AddItem(item);

            SetShoppingCart(cart);

            return RedirectToAction("Count");
        }

        [HttpPost]
        public ActionResult Update(List<OrderItem> items)
        {
            var cart = GetShoppingCart();
            cart.Update(items);

            SetShoppingCart(cart);

            return RedirectToAction("Calculate");
        }

        public ActionResult Calculate()
        {
            var cart = GetShoppingCart();
            var subtotal = cart.Subtotal;

            return PartialView(subtotal);
        }

        public ActionResult CheckoutTransition()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Checkout");
            else
                return RedirectToAction("SaveCart");
        }

        [Authorize]
        public ActionResult SaveCart()
        {
            var sessionHandler = new SessionHandler(Session);
            Order order = sessionHandler.Cart;

            SetShoppingCart(new Cart(order));

            sessionHandler.DeleteCart();

            return RedirectToAction("Index", "Checkout");
        }

        private void SetShoppingCart(Cart cart)
        {
            if (User.Identity.IsAuthenticated)
                orderService.AddOrUpdateCart(User.Identity.GetUserId(), cart.Order);
            else
            {
                var sessionHandler = new SessionHandler(Session);
                sessionHandler.Cart = cart.Order;
            }
        }

        private Cart GetShoppingCart()
        {
            Order order;
            if (User.Identity.IsAuthenticated)
            {
                order = orderService.GetCart(User.Identity.GetUserId());
            }
            else
            {
                var sessionHandler = new SessionHandler(Session);
                order = sessionHandler.Cart;
            }
            return new Cart(order);
        }
    }
}

Web/Source/BloomSales.Web.Store/Controllers/StoreController.cs
using BloomSales.Services.Contracts;
using BloomSales.Services.Proxies;
using BloomSales.Web.Store.Controllers.Business;
using BloomSales.Web.Store.Models;
using System.Web.Mvc;

namespace BloomSales.Web.Store.Controllers
{
    public class StoreController : Controller
    {
        private IInventoryService inventoryService;
        private ILocationService locationService;

        public StoreController()
        {
            inventoryService = new InventoryClient();
            locationService = new LocationClient();
        }

        public ActionResult Index(string categoryName = "")
        {
            return View((object)categoryName);
        }

        public ActionResult Catalog(string categoryName)
        {
            if (string.IsNullOrEmpty(categoryName))
                return PartialView("CatalogFrontPage");
            else
                return Products(categoryName);
        }

        public ActionResult CategoriesList()
        {
            var retriever = new CategoriesRetriever(inventoryService);
            var categoriesList = retriever.GetList();
            return PartialView(categoriesList);
        }

        public ActionResult Products(string categoryName)
        {
            var products = inventoryService.GetProductsByCategory(categoryName);

            return PartialView(products);
        }

        public ActionResult ProductDetails(int id, decimal unitPrice)
        {
            var productDetails = new ProductDetailsViewModel(id, unitPrice);

            return PartialView(productDetails);
        }
    }
}

Web/Source/BloomSales.Web.Store/Views/ShoppingCart/Calculate.cshtml
@model System.Decimal?

<div>
    <h2 class="text-center text-danger">$@string.Format("{0:n}", Model)</h2>
</div>

Web/Source/BloomSales.Web.Store/Views/ShoppingCart/Count.cshtml
@model System.Int32?

<ul style="padding-left:1em" class="nav navbar-right nav-list">

    @if (Model == 0 || Model == null)
    {
        <li class="disabled">
            <a href="#">
                <span style="font-size:1.4em; padding-top:4px;" class="glyphicon glyphicon-shopping-cart"></span>
            </a>
        </li>
    }
    else
    {
        <li>
            <a href="@Url.Action("Index", "ShoppingCart")">
                <sup>
                    <span style="font-size:0.8em;" class="navbar-nav badge">@Model</span>
                </sup>
                <span style="font-size:1.4em; padding-top:4px;" class="glyphicon glyphicon-shopping-cart"></span>
            </a>
        </li>
    }
</ul>

Web/Source/BloomSales.Web.Store/Views/ShoppingCart/Index.cshtml
@model Tuple<List<BloomSales.Data.Entities.OrderItem>, IEnumerable<BloomSales.Data.Entities.Product>>

@{
    ViewBag.Title = "Shopping Cart";

    var productIt = Model.Item2.GetEnumerator();
}

<h2>Shopping Cart</h2>

<div class="container" style="padding-bottom:3em;">

    <div class="col-md-8">
        <div class="row" style="padding-top:3em;">
            <div class="col-md-1">
                <h4 class="text-muted">#</h4>
            </div>
            <div class="col-md-7">
                <h4 class="text-center text-muted">Item Name</h4>
            </div>
            <div class="col-md-2">
                <h4 class="text-center text-muted">Unit Price</h4>
            </div>
            <div class="col-md-2">
                <h4 class="text-center text-muted">Quantity</h4>
            </div>
        </div>
        @using (Ajax.BeginForm("Update", "ShoppingCart", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "subtotal", InsertionMode = InsertionMode.Replace }, new { id = "cartItems" }))
        {
            @Html.AntiForgeryToken();

            for (int i = 0; i < Model.Item1.Count; i++)
            {
                productIt.MoveNext();

                @Html.Hidden(string.Format("items[{0}].Index", @i), @i);
                <div style="padding-bottom:20px;" class="row form-group">
                    @Html.Hidden(string.Format("items[{0}].ProductID", @i), Model.Item1[i].ProductID)
                    <hr />
                    <div class="col-md-1">
                        <h4>@(i + 1)</h4>
                    </div>
                    <div class="col-md-2">

                        <img src="@productIt.Current.ImageUrl" alt="@productIt.Current.Name"
                             class="img-responsive" style="padding-top:10px;" />
                    </div>
                    <div class="col-md-5">
                        <h4>
                            <a href="javascript:showDetails(@productIt.Current.ID);">@productIt.Current.Name</a>
                        </h4>

                        <p>@productIt.Current.Producer</p>
                    </div>

                    <div class="col-md-2">
                        <div class="row">
                            @Html.Hidden(string.Format("items[{0}].UnitPrice", @i), Model.Item1[i].UnitPrice)
                            <h4 class="text-center">$@string.Format("{0:n}", Model.Item1[i].UnitPrice)</h4>
                        </div>
                        <div class="row">
                            @if (@Model.Item1[i].Discount > 0)
                            {
                                <p class="text-center">@(Model.Item1[i].Discount * 100)% Discount</p>
                            }
                        </div>
                    </div>

                    <div class="col-md-2">
                        @Html.TextBox(string.Format("items[{0}].Quantity", @i),
                                      Model.Item1[i].Quantity,
                                      new { type = "number", min = "0", @class = "form-control center-block", onchange = "onQuantityChange()" })
                    </div>
                </div>

            }

        }
    </div>

    <div class="col-md-1">
    </div>
    <div class="col-md-3">
        <div class="row" style="padding-top:2.5em;">
        </div>
        <div class="panel panel-warning">
            <div class="panel-heading">
                <div class="panel-title text-center">Subtotal (@Model.Item1.Count Items)</div>
            </div>
            <div id="subtotal" class="panel-body">
                @Html.Action("Calculate")
            </div>
        </div>
        <div class="well">
            <div class="row" style="padding:1em;">
                @Html.ActionLink("Proceed to Checkout", "CheckoutTransition", new { },
                                 new { @class = "btn btn-primary center-block", role = "button" })
            </div>
            <div class="row">
                <p class="text-center">or</p>
            </div>

            <div class="row">
                <p class="text-center">
                    @Html.ActionLink("Go Back to Shopping", "Index", "Store")
                </p>
            </div>
        </div>
    </div>
</div>


@Html.Partial("ProductDetailsModal")


@section scripts
{
    <script type="text/javascript">
        function onQuantityChange() {
            $("#cartItems").submit();
        }

        function showDetails(productID) {
            var modal = $("#productDetailsModal #productDetails");
            modal.html("<p>Loading product details ...</p>");
            modal.load("@Url.Action("Details", "Product")", { id : productID });
            $("#productDetailsModal").modal("show");
        }
    </script>
}